services:
  db:
    image: postgres:16-alpine
    container_name: task_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: task_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  aspire_dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: task_aspire_dashboard
    ports:
      - "18888:18888" # Dashboard Web UI
      - "4317:18889"  # Standard OTLP gRPC endpoint
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
      - DASHBOARD__FRONTEND__AUTHMODE=Unsecured
      - DASHBOARD__OTLP__AUTHMODE=Unsecured
      - DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://0.0.0.0:18889

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_api_app
    restart: always
    ports:
      - "5131:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
      - OTEL_SERVICE_NAME=TaskApi
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire_dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      aspire_dashboard:
        condition: service_started

volumes:
  postgres_data: